import json
import re

input_file = "./cleaned-design-tokens.json"
output_file = "./design-tokens.css"

with open(input_file, "r") as f:
    data = json.load(f)


def resolve_reference(ref_str, palette):
    match = re.match(r"\{color pallete\.(\w+)\.(\w+)\}", ref_str)
    if match:
        palette_name, shade = match.groups()
        value = palette[palette_name][shade]
        if isinstance(value, dict):
            return value["value"]
        return value
    return ref_str


def resolve_reference_to_var(ref_str):
    match = re.match(r"\{color pallete\.(\w+)\.(\w+)\}", ref_str)
    if match:
        palette_name, shade = match.groups()
        return f"var(--color-{palette_name}-{shade})"
    return ref_str


def build_color_palette(source):
    palette_data = source["color pallete"]
    resolved = {}

    for palette_name, shades in palette_data.items():
        shade_map = {}
        for shade_name, shade_entry in shades.items():
            raw = shade_entry["value"]
            if raw.startswith("{"):
                shade_map[shade_name] = resolve_reference(raw, palette_data)
            else:
                shade_map[shade_name] = raw
        resolved[palette_name] = shade_map

    return resolved


def generate_color_palette_vars(palette):
    lines = []
    for palette_name, shades in palette.items():
        for shade_name, value in shades.items():
            css_var = f"--color-{palette_name}-{shade_name}"
            lines.append(f"  {css_var}: {value};")
    return "\n".join(lines)


def generate_semantic_color_vars(color_variables, palette):
    lines = []

    def flatten_colors(obj, prefix=""):
        for key, value in obj.items():
            if isinstance(value, dict):
                if "type" in value and value["type"] == "color":
                    raw = value["value"]
                    if raw.startswith("{"):
                        resolved = resolve_reference_to_var(raw)
                    else:
                        resolved = raw
                    lines.append(f"  {prefix}-{key}: {resolved};")
                else:
                    flatten_colors(value, f"{prefix}-{key}")

    bg = color_variables.get("bg", {})
    flatten_colors(bg, "--color")

    text = color_variables.get("text", {})
    flatten_colors(text, "--color")

    return "\n".join(lines)


def generate_font_family_vars(color_variables, palette):
    font_config = color_variables.get("font", {})
    lines = []
    for key, value in font_config.items():
        if isinstance(value, dict) and "value" in value:
            lines.append(f"  --font-{key}: {value['value']};")
    return "\n".join(lines)


def generate_typography_classes(fonts):
    classes = []

    for name, token in fonts.items():
        if token.get("type") != "custom-fontStyle":
            continue
        v = token["value"]

        font_size = v.get("fontSize", 16)
        line_height = v.get("lineHeight", font_size)
        font_weight = v.get("fontWeight", 400)
        letter_spacing = v.get("letterSpacing", 0)
        font_family = v.get("fontFamily", "Inter")

        cls = f""".{name} {{
  font-size: {font_size}px;
  line-height: {line_height}px;
  font-weight: {font_weight};
  letter-spacing: {letter_spacing}px;
  font-family: {font_family}, sans-serif;
}}"""
        classes.append(cls)

    return "\n\n".join(classes)


palette = build_color_palette(data)

color_palette_css = generate_color_palette_vars(palette)
semantic_color_css = generate_semantic_color_vars(
    data["color variables"], palette)
font_family_css = generate_font_family_vars(data["color variables"], palette)
typography_css = generate_typography_classes(data["font"])

css = f"""/* Do not edit this file this is an auto generated file */

@theme {{
{color_palette_css}
{semantic_color_css}
{font_family_css}
}}

{typography_css}
"""

with open(output_file, "w") as f:
    f.write(css)

print(f"Generated {output_file}")
